---
- task:
  name: Ensure application variables are loaded
  include_vars: "{{ item }}"
  with_first_found:
    - variables/application.yml

- task:
  name: Ensure main is created
  template:
    src: templates/main.py.j2
    dest: "{{ output.path }}/{{ application.name }}.py"