---
- task:
  name: Ensure application variables are loaded
  include_vars: "{{ item }}"
  with_first_found:
    - variables/application.yml

- task:
  name: look for config definition
  stat:
    path: variables/config.yml
  register: declaration

- task:
  name: Ensure config variables are loaded
  include_vars: "{{ item }}"
  with_first_found:
    - variables/config.yml
  when: declaration.stat.exists

- task:
  name: Ensure main is created
  template:
    src: templates/main.py.j2
    dest: "{{ output.path }}/{{ application.name }}.py"