---
- name: Ensure application variables are loaded
  include_vars: "{{ item }}"
  with_first_found:
    - variables/application.yml

- name: look for config definition
  stat:
    path: variables/config.yml
  register: declaration

- name: Ensure config variables are loaded
  include_vars: "{{ item }}"
  with_first_found:
  - variables/config.yml
  when: declaration.stat.exists

- name: Ensure project directory exists
  file:
    path: "{{ output.path }}"
    state: directory

- name: Ensure main is created
  template:
    src: templates/main.py.j2
    dest: "{{ output.path }}/{{ application.name }}.py"

- name: Ensure requirements file is created
  template:
    src: templates/requirements.txt.j2
    dest: "{{ output.path }}/requirements.txt"