---
- name: Look for requirements file
  stat:
    path: "{{ output.path }}/requirements.txt"
  register: requirements_file

- name: Ensure Python requirements are met
  pip:
    chdir: "{{ output.path }}"
    requirements: requirements.txt
  when:  application.virtualenv is undefined and requirements_file.stat.exists

- name: Ensure virtualenv folder is present
  file:
    path: "{{ output.path }}/venv"
    state: directory

- name: Ensure virtualenv is created
  pip:
    chdir: "{{ output.path }}"
    requirements: requirements.txt
    virtualenv: "{{ output.path }}/venv"
    virtualenv_python: python3.7
  when: application.virtualenv is defined and requirements_file.stat.exists